id: P0F028242
initial_creation_type: input
source_metadata:
  title: Buddhagupta
  language: pt
  description: Instructions
  volume:
    91cf172505d24a02b2b9e8b7e5301cec:
      title: An Extensive Commentary on the Four Immeasurables
      parent: Instructions
created_at: '2022-03-01T02:13:36.519965'
last_modified_at: '2022-03-01T02:13:36.519967'
